src/objects/DataCenter__c.object
<CustomObject>
    <label>DataCenter</label>
    <nameField>
        <label>DataCenter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DateCenters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Server__c.object
<CustomObject>
    <fields>
        <fullName>Power_Down__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Power Down</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Power_LeveL__c</fullName>
        <label>Power LeveL</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Server</label>
    <nameField>
        <label>Sever Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Server_Map_Record__c.object
<CustomObject>
    <fields>
        <fullName>DataCenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DataCenter</label>
        <referenceTo>DataCenter__c</referenceTo>
        <relationshipLabel>Server Map Records</relationshipLabel>
        <relationshipName>Server_Map_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Server__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sever</label>
        <referenceTo>Server__c</referenceTo>
        <relationshipLabel>Server Map Records</relationshipLabel>
        <relationshipName>Server_Map_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Server Map Record</label>
    <nameField>
        <label>Server Map Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Server Map Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TargetServersRecordCtrl.cls
public with sharing class TargetServersRecordCtrl {
	
	private DataCenter__c dataCenter {set; get;}
		public List<Server_Map_Record__c> serverMapRecords {get; set;}
		public List<server__c> servers {set; get;}
		
		public TargetServersRecordCtrl(ApexPages.StandardController stdCtrl){
			this.dataCenter = (DataCenter__c)stdCtrl.getRecord();
			
			serverMapRecords = [select server__c from Server_Map_Record__c where id =:dataCenter.id];
			servers = [select id , name, power_down__c, power_level__c from server__c where id in (select server__c from Server_Map_Record__c where id =:dataCenter.id)];
			
		}
	
	
}