src/objects/DataCenter__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server_Number__c</fullName>
        <label>Server Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DataCenter</label>
    <nameField>
        <label>DataCenter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DateCenters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecordCtrl.cls
public with sharing class RecordCtrl {
		
		public list<DataCenter__c> dataCenters {set; get;}
		public Integer second {set; get;}
		public String SelectedValue {get; set;}
		public Id TargetDataCenterID {get; set;}
		
		public RecordCtrl(){
			second = 0;
			//TargetDataCenterID = '';
			dataCenters = [select name, location__c , server_number__c from DataCenter__c];
		} 
		  
		public void pollerCall(){ 
			second += 7;
		}
		
		public pageReference setTargetId(){
			//this.TargetDataCenterID = TargetDataCenterID;
			return null;
		}
		
		public pageReference toTargetDataCenter(){
			//id targetId = id.valueOf(TargetDataCenterID);
			DataCenter__c dataCenter = new DataCenter__c(id=TargetDataCenterID);
			PageReference actionPage = new ApexPages.StandardController(dataCenter).view();
        	actionPage.setRedirect(true);
        	return actionPage;
			
			/*PageReference pg = new PageReference('/apex/RecordViewPage');
			pg.getParameters().put('id',TargetDataCenterID);
			pg.setRedirect(true);
			return pg;*/
		}
		
}